
import { GoogleGenAI, Modality } from "@google/genai";
import { AspectRatio } from "../types";

export const generateImage = async (prompt: string, aspectRatio: AspectRatio) => {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt,
        config: {
            numberOfImages: 1,
            outputMimeType: 'image/jpeg',
            aspectRatio: aspectRatio,
        },
    });

    const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
    return `data:image/jpeg;base64,${base64ImageBytes}`;
};

export const editImage = async (prompt: string, imageBase64: string, mimeType: string) => {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                {
                    inlineData: {
                        data: imageBase64,
                        mimeType: mimeType,
                    },
                },
                {
                    text: prompt,
                },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            const base64ImageBytes: string = part.inlineData.data;
            return `data:image/png;base64,${base64ImageBytes}`;
        }
    }
    throw new Error("No image was generated by the model.");
};

export const getBotResponse = async (prompt: string) => {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
            systemInstruction: "You are Reze, a friendly and helpful customer service assistant for this AI image generation application. Your purpose is to help users, provide creative ideas for prompts, and explain how to use the app's features like the prompt enhancer. Do not go off-topic. Be concise, encouraging, and use markdown for formatting if it helps clarity.",
        }
    });
    return response.text;
};

// Fix: Implement generateVideoFromImage for video generation.
export const generateVideoFromImage = async (
    prompt: string,
    imageBase64: string,
    mimeType: string,
    aspectRatio: '16:9' | '9:16'
) => {
    // Per guidelines for Veo, create a new instance before API call
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const operation = await ai.models.generateVideos({
        model: 'veo-3.1-fast-generate-preview',
        prompt,
        image: {
            imageBytes: imageBase64,
            mimeType: mimeType,
        },
        config: {
            numberOfVideos: 1,
            resolution: '720p',
            aspectRatio: aspectRatio,
        }
    });
    return operation;
};

// Fix: Implement pollVideoOperation to check video generation status.
export const pollVideoOperation = async (operation: any) => {
    // Per guidelines for Veo, create a new instance before API call
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const updatedOperation = await ai.operations.getVideosOperation({ operation });
    return updatedOperation;
};
